// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ConfirmableController from "./confirmable_controller"
application.register("confirmable", ConfirmableController)

import ToggleableController from "./toggleable_controller"
application.register("toggleable", ToggleableController)
