services:
  web:
    build: .
    ports:
      - "2222:3000"
    volumes: 
      - .:/usr/src/app
      - gem_cache:/gems
    env_file:
      - .env.development.local

  redis:
    image: redis

  database:
    image: postgres
    env_file:
        - .env.development.local
    volumes:
     - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  gem_cache: