services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "2222:3000"
    volumes: 
      - .:/usr/src/app
      - gem_cache:/gems
    env_file:
      - .env.production.local
    depends_on:
      - database
      - redis

  redis:
    image: redis

  database:
    image: postgres:alpine
    env_file:
      - .env.production.local
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  gem_cache: